from app.models import db, Trade, portfolio
from datetime import datetime

def seed_trades():
    demo_trade_1 = Trade(portfolio_id=1, ticker="AAPL", execution_price=100, execution_type="BUY", quantity=10, transaction_date=datetime(2021, 9, 3, 12, 1, 1))
    demo_trade_2 = Trade(portfolio_id=1, ticker="MSFT", execution_price=200, execution_type="BUY", quantity=10, transaction_date=datetime(2021, 9, 4, 12, 1, 1))
    demo_trade_3 = Trade(portfolio_id=1, ticker="GOOG", execution_price=300, execution_type="BUY", quantity=10, transaction_date=datetime(2021, 9, 5, 12, 1, 1))
    demo_trade_4 = Trade(portfolio_id=1, ticker="AMZN", execution_price=400, execution_type="BUY", quantity=10, transaction_date=datetime(2021, 9, 6, 12, 1, 1))
    demo_trade_5 = Trade(portfolio_id=1, ticker="NFLS", execution_price=500, execution_type="BUY", quantity=10, transaction_date=datetime(2021, 9, 7, 12, 1, 1))
    # demo_trade_6 = Trade(portfolio_id=1, ticker="BTC", execution_price=65000, execution_type="SELL", quantity=10, transaction_date=datetime(2021, 9, 8, 12, 1, 1))
    demo_trade_7 = Trade(portfolio_id=1, ticker="GME", execution_price=500, execution_type="SELL", quantity=25, transaction_date=datetime(2021, 9, 9, 12, 1, 1))
    demo_trade_8 = Trade(portfolio_id=1, ticker="F", execution_price=17, execution_type="BUY", quantity=100, transaction_date=datetime(2021, 9, 10, 12, 1, 1))
    demo_trade_9 = Trade(portfolio_id=1, ticker="DOGE", execution_price=1, execution_type="SELL", quantity=25000, transaction_date=datetime(2021, 9, 11, 12, 1, 1))
    # demo_trade_10 = Trade(portfolio_id=1, ticker="SPY", execution_price=450, execution_type="SELL", quantity=15, transaction_date=datetime(2021, 9, 12, 12, 1, 1))
    demo_trade_11 = Trade(portfolio_id=1, ticker="VXX", execution_price=30, execution_type="SELL", quantity=100, transaction_date=datetime(2021, 9, 13, 12, 1, 1))
    demo_trade_12 = Trade(portfolio_id=1, ticker="SQ", execution_price=250, execution_type="SELL", quantity=25, transaction_date=datetime(2021, 9, 13, 12, 1, 1))
    demo_trade_13 = Trade(portfolio_id=1, ticker="ROKU", execution_price=325, execution_type="SELL", quantity=5, transaction_date=datetime(2021, 9, 14, 12, 1, 1))
    demo_trade_14 = Trade(portfolio_id=1, ticker="AAL", execution_price=15, execution_type="BUY", quantity=200, transaction_date=datetime(2021, 9, 14, 12, 1, 1))
    demo_trade_15 = Trade(portfolio_id=1, ticker="FB", execution_price=360, execution_type="BUY", quantity=10, transaction_date=datetime(2021, 9, 15, 12, 1, 1))
    demo_trade_16 = Trade(portfolio_id=3, ticker="H", execution_price=70, execution_type="BUY", quantity=45, transaction_date=datetime(2021, 9, 15, 12, 1, 1))
    demo_trade_17 = Trade(portfolio_id=3, ticker="MAR", execution_price=145, execution_type="SELL", quantity=25, transaction_date=datetime.today())
    demo_trade_18 = Trade(portfolio_id=3, ticker="IHG", execution_price=70, execution_type="SELL", quantity=35, transaction_date=datetime.today())
    demo_trade_19 = Trade(portfolio_id=4, ticker="CRC", execution_price=25, execution_type="BUY", quantity=10, transaction_date=datetime.today())
    demo_trade_20 = Trade(portfolio_id=4, ticker="HMPT", execution_price=6, execution_type="SELL", quantity=100, transaction_date=datetime.today())
    demo_trade_21 = Trade(portfolio_id=5, ticker="ALKS", execution_price=31, execution_type="SELL", quantity=250, transaction_date=datetime.today())
    demo_trade_22 = Trade(portfolio_id=5, ticker="AMBA", execution_price=150, execution_type="SELL", quantity=150, transaction_date=datetime.today())
    demo_trade_23 = Trade(portfolio_id=5, ticker="SEDG", execution_price=265, execution_type="BUY", quantity=50, transaction_date=datetime.today())
    demo_trade_24 = Trade(portfolio_id=5, ticker="FIVE", execution_price=236, execution_type="BUY", quantity=25, transaction_date=datetime.today())
    demo_trade_25 = Trade(portfolio_id=5, ticker="MOS", execution_price=37, execution_type="SELL", quantity=350, transaction_date=datetime.today())

    db.session.add(demo_trade_1)
    db.session.add(demo_trade_2)
    db.session.add(demo_trade_3)
    db.session.add(demo_trade_4)
    db.session.add(demo_trade_5)
    # db.session.add(demo_trade_6)
    db.session.add(demo_trade_7)
    db.session.add(demo_trade_8)
    db.session.add(demo_trade_9)
    # db.session.add(demo_trade_10)
    db.session.add(demo_trade_11)
    db.session.add(demo_trade_12)
    db.session.add(demo_trade_13)
    db.session.add(demo_trade_14)
    db.session.add(demo_trade_15)
    db.session.add(demo_trade_16)
    db.session.add(demo_trade_17)
    db.session.add(demo_trade_18)
    db.session.add(demo_trade_19)
    db.session.add(demo_trade_20)
    db.session.add(demo_trade_21)
    db.session.add(demo_trade_22)
    db.session.add(demo_trade_23)
    db.session.add(demo_trade_24)
    db.session.add(demo_trade_25)

    db.session.commit()


def undo_trades():
    db.session.execute('TRUNCATE trades RESTART IDENTITY CASCADE;')
    db.session.commit()
